_target_: src.models.gcn_module.GCNModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 1e-5

encoder:
  _target_: src.models.components.gnns.SimpleGCNEncoder
  in_size: 1433
  hid_size: 300
  out_size: 7
  # num_layers: 3

num_classes: 7

# compile model for faster training with pytorch 2.0
compile: false
